### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by Mardoqueu** [halysongoncalves/Material-Design-Example#2]
Honestly, where may I change the fragments' name? the tabs

**Comment by halysongoncalves** [comment]
Hello,

Within (resources/string/strings_fragments) three strings that specify the name:

     <! - Sectios Tabs ->
     <string name = "fragment_home_fragment1_title"> Fragment 1 </ string>
     <string name = "fragment_home_fragment2_title"> Fragment 2 </ string>
     <string name = "fragment_home_fragment3_title"> Fragment 3 </ string>

To change the name of the tabs, simply replace the value you want those strings!
